name: 'release'

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
  
    - name: Get tag version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      shell: bash

    - name: Setup Arduino CLI
      run: choco install arduino-cli --version=0.12.1 -y    
    - name: Install Arduino core
      run: arduino-cli core install arduino:avr

    - name: Build Firmware - Full step
      run: arduino-cli.exe compile -b arduino:avr:nano:cpu=atmega328 -v --build-path ${{ github.workspace }}\Embedded\Builds\FullStep\ ${{ github.workspace }}\Embedded\MaxMix\MaxMix.ino

    - name: Build Firmware - Half step
      run: arduino-cli.exe compile -b arduino:avr:nano:cpu=atmega328 -v --build-path ${{ github.workspace }}\Embedded\Builds\HalfStep\ --build-properties build.extra_flags=-DHALF_STEP ${{ github.workspace }}\Embedded\MaxMix\MaxMix.ino

    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v1.0.2
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1
    - name: Setup MSBuild ExtensionPack
      run: choco install msbuild.extensionpack --version=4.0.15.0 -y    
      
    - name: Restore Application packages
      run: nuget restore Desktop\Application\MaxMix.sln
    - name: Build Application
      run: msbuild Desktop\Build.msbuild -p:SolutionDir=Application -p:Version=${{ steps.get_version.outputs.VERSION }}.0 -p:Configuration=Debug -p:Platform="Any CPU"

    - name: Restore DriverInstaller packages
      run: nuget restore Desktop\DriverInstaller\DriverInstaller.sln
    - name: Build DriverInstaller
      run: msbuild Desktop\Build.msbuild -p:SolutionDir=DriverInstaller -p:Version=${{ steps.get_version.outputs.VERSION }}.0 -p:Configuration=Debug -p:Platform="Any CPU"

    - name: Restore FirmwareInstaller packages
      run: nuget restore Desktop\FirmwareInstaller\FirmwareInstaller.sln
    - name: Build FirmwareInstaller
      run: msbuild Desktop\Build.msbuild -p:SolutionDir=FirmwareInstaller -p:Version=${{ steps.get_version.outputs.VERSION }}.0 -p:Configuration=Debug -p:Platform="Any CPU"

    - name: Setup Advanced Installer
      run: choco install advanced-installer --version=17.1.2 -y
    - name: Add Advanced Installer to path
      run: echo ::add-path::"C:/Program Files (x86)/Caphyon/Advanced Installer 17.1.2/bin/x86"
    - name: Register Advanced Installer
      run: AdvancedInstaller.com /register ${{secrets.ADVANCEDINSTALLER_LICENSE}}
    
    - name: Set Installer version
      run: AdvancedInstaller.com /edit Desktop\Installer\Maxmix.aip /SetVersion ${{ steps.get_version.outputs.VERSION }}
    
    - name: Build Installer
      run: AdvancedInstaller.com /build Desktop\Installer\Maxmix.aip
   
    - name: Create Release
      id: create-release
      uses: actions/create-release@v1.1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        release_name: ${{ steps.get_version.outputs.VERSION }}
        body: ''
        draft: false
        prerelease: true

    - name: Upload Release Assets - Installer
      id: upload-release-assets-installer
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: Desktop\Installer\Builds\Maxmix.msi
        asset_name: Maxmix.${{ steps.get_version.outputs.VERSION }}.msi
        asset_content_type: application/zip

    - name: Upload Release Assets - Firmware (FullStep)
      id: upload-release-assets-firmware-fullstep
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: Embedded\Builds\FullStep\MaxMix.ino.hex
        asset_name: Maxmix.${{ steps.get_version.outputs.VERSION }}.hex
        asset_content_type: application/zip

    - name: Upload Release Assets - Firmware (HalfStep)
      id: upload-release-assets-firmware-halfstep
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: Embedded\Builds\HalfStep\MaxMix.ino.hex
        asset_name: Maxmix.${{ steps.get_version.outputs.VERSION }}_Half-step.hex
        asset_content_type: application/zip
